version: '3.8'

services:
  api:
    container_name: vortexa-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=${PORT}
      - RSA_BITS=${RSA_BITS}
      - RSA_PASSPHRASE=${RSA_PASSPHRASE}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - HASH_ROUNDS=${HASH_ROUNDS}
    ports:
      - ${PORT}:${PORT}
  db:
    image: postgres:13.13
    container_name: vortexa-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_EXPOSE_PORT}:5432
  adminer:
    image: adminer:4.8.1-standalone
    container_name: vortexa-adminer
    restart: always
    ports:
     - 8080:8080
  redis:
    container_name: vortexa-redis
    restart: always
    ports:
      - ${REDIS_EXPOSE_PORT}:6379