version: '3.8'

services:
  api:
    networks:
      - vortexa-network
    build:
      target: development
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
  db:
    networks:
      - vortexa-network
    volumes:
      - ./DATA/DB_DATA:/var/lib/postgresql/data
  adminer:
    networks:
      - vortexa-network
  redis:
    image: redis/redis-stack:6.2.6-v11
    networks:
      - vortexa-network
    volumes:
      - ./DATA/REDIS_DATA:/data
    ports:
      - ${REDIS_INSIGHT_EXPOSE_PORT}:8001


networks:
  vortexa-network:
    name: vortexa-network
    driver: bridge