version: '3.8'

services:
  api:
    networks:
      - vortexa-network
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
  db:
    networks:
      - vortexa-network
    volumes:
      - ./DATA/DB_DATA:/var/lib/postgresql/data
  adminer:
    networks:
      - vortexa-network

networks:
  vortexa-network:
    name: vortexa-network
    driver: bridge